apiVersion: vshn.appcat.vshn.io/v1
kind: VSHNNextcloud
metadata:
  name: appcat-demo-nextcloud-appuio-simple
  namespace: {{ .Release.Namespace }}
spec:
  parameters:
    service:
      fqdn:
        - appuio-nextcloud-demo.apps.cloudscale-lpg-2.appuio.cloud
      version: "32"
      postgreSQLParameters:
        encryption:
          enabled: true
    size:
      plan: standard-2
  writeConnectionSecretToRef:
    name: nextcloud-creds
